name: Health check

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 6 * * 6"  # Every Saturday at 06:00 UTC
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv and jq
        run: |
          pip install uv jq

      - name: Install package
        run: |
          uv pip install -e . --system

      - name: Run health check
        run: |
          domene-expired --json | jq -e '.[0].domain' > /dev/null
